---
- name: Strongswan create ipsec.conf  
  template: 
    src: 'etc/ipsec.conf.j2'
    dest: "/etc/ipsec.conf"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Strongswan create ipsec.secrets
  shell: echo user{{ item }} ':' EAP \"`pwgen 8 1`\" >> /etc/ipsec.secrets
  with_sequence: start=1 end=50

- name: Change mode for ipsec.secrets
  file:
    path: /etc/ipsec.secrets
    state: touch
    mode: 0640

- name: Create ipsec synlink for RedHat
  file:
    src: /usr/sbin/strongswan
    dest: /usr/sbin/ipsec
    state: link
  when: ("{{ ansible_os_family }}" == 'RedHat')

- name: Create keys and certificates
  shell: |
         ipsec pki --gen --type rsa --size 4096 --outform pem > /etc/ipsec.d/private/ca-key.pem
         ipsec pki --self --ca --lifetime 3650 --in /etc/ipsec.d/private/ca-key.pem --type rsa --dn \"CN=My root CA\" --outform pem > /etc/ipsec.d/cacerts/ca-cert.pem
         ipsec pki --gen --type rsa --size 4096 --outform pem > /etc/ipsec.d/private/server-key.pem
         ipsec pki --pub --in /etc/ipsec.d//private/server-key.pem --type rsa | ipsec pki --issue --lifetime 1825 --cacert /etc/ipsec.d/cacerts/ca-cert.pem --cakey /etc/ipsec.d/private/ca-key.pem --dn \"CN={{ ansible_default_ipv4.address }}\" --san \"{{ ansible_default_ipv4.address }}\" --flag serverAuth --flag ikeIntermediate --outform pem > /etc/ipsec.d/certs/server-cert.pem
