---
- name: Set systems variables
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes        
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    sysctl_set: yes        
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    sysctl_set: yes        
  sysctl:
    name: net.ipv4.ip_no_pmtu_disc
    value: 1
    sysctl_set: yes        

- name: Set firewall rules
  iptables:
    chain: FORWARD
    in_interface: tun+
    out_interface: "{{ ansible_default_ipv4.interface }}"
    source: 10.10.10.0/0
    destination: 0.0.0.0/0
    jump: ACCEPT
  iptables:
    chain: FORWARD
    in_interface: "{{ ansible_default_ipv4.interface }}"
    out_interface: tun+
    source: 0.0.0.0/0
    destination: 10.10.10.0/0
    jump: ACCEPT
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ ansible_default_ipv4.interface }}"
    source: 10.10.10.0/0
    jump: SNAT
    to_source: "{{ ansible_default_ipv4.address }}"
