mysql_root_password: "123"
db_name: "owlsa"
db_user: "owlsa"
db_password: "123OwlsA456"
back_serv_ip: "172.31.23.118"
db_host: "172.31.29.131"
site_name: "owlsa.vitagan.ru"
wp_user_1: "Vit"
wp_mail_1: "info@vitagan.ru"
wp_pass_1: "123ViT456"
wp_user_2: "Vitard"
wp_mail_2: "vetoslav@yandex.ru"
wp_pass_2: "123VitarD456"
wp_user_3: "Vitagan"
wp_mail_3: "vetagan@gmail.com"
wp_pass_3: "123VetaGan456"
