- name: Install Nginx
  apt: 
    name: nginx
- name: Push nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644 owner=root group=root
- name: Push nginx virtual host configuration
  template: src=vhost.conf.j2 dest=/etc/nginx/conf.d/vhost.conf mode=0644 owner=root group=root
- name: Push nginx proxy configuration
  template: src=proxy.conf.j2 dest=/etc/nginx/conf.d/proxy.conf mode=0644 owner=root group=root
- name: delete default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: "absent"
- name: Start Nginx
  systemd: name=nginx enabled=yes state=restarted
